title: "SemEval-2021 Task 10: Source-Free Domain Adaptation for Semantic Processing"
email: source-free-domain-adaptation-participants@googlegroups.com
baseurl: ""
url: source-free-domain-adaptation.github.io
codalab_url: https://competitions.codalab.org/competitions/26152
group_url: https://groups.google.com/forum/#!forum/source-free-domain-adaptation-participants/
