# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2021-02-24 01:32:02 -0700 by egoitz:
gem "jekyll", "~> 4.2"
